// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// qrencode_raw
NumericMatrix qrencode_raw(std::string to_encode);
RcppExport SEXP qrencoder_qrencode_raw(SEXP to_encodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type to_encode(to_encodeSEXP);
    __result = Rcpp::wrap(qrencode_raw(to_encode));
    return __result;
END_RCPP
}
