# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Encodes a string as a QR code
#' @param to_encode character string to encode
#' @export
qrencode_raw <- function(to_encode) {
    .Call('qrencoder_qrencode_raw', PACKAGE = 'qrencoder', to_encode)
}

