# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Encodes a string as a QR code
#' @description Encodes a string as a QR coder
#' @param to_encode character string to encode
#' @param version version of the symbol. If \code{0}, the library chooses the
#'        minimum version for the given input data.
#' @param level error correction level (\code{0} - \code{3}, lowest to highest)
#' @param hint tell the library how Japanese Kanji characters should be
#'        encoded. If "\code{3}", the library assumes that the
#'        given string contains Shift-JIS characters and encodes them in
#'        Kanji-mode. If "\code{2}" is given, all of non-alphanumerical
#'        characters will be encoded as is. If you want to embed UTF-8
#'        string, choose this. Other mode will cause EINVAL error.\cr\cr
#'        "\code{0}" is "numeric mode", "\code{1}" is "alphanumeric mode",
#'        "\code{5}" is "ECI mode".
#' @param caseinsensitive case-sensitive(\code{1}) or not(\code{0}).
#' @seealso \url{http://www.qrcode.com/en/about/version.html}
#' @export
qrencode_raw <- function(to_encode, version = 0L, level = 0L, hint = 2L, caseinsensitive = 1L) {
    .Call('qrencoder_qrencode_raw', PACKAGE = 'qrencoder', to_encode, version, level, hint, caseinsensitive)
}

